import { CategoryOption, SourceOption } from "../types"

export const NYT_SOURCES: SourceOption[] = [
  {
    id: "the new york times",
    name: "The New York Times",
    category: "news",
  },
  {
    id: "wirecutter",
    name: "Wirecutter",
    category: "reviews",
  },
  {
    id: "international new york times",
    name: "International New York Times",
    category: "news",
  },
  {
    id: "reuters",
    name: "Reuters",
    category: "news",
  },
  {
    id: "ap",
    name: "AP",
    category: "news",
  },
  {
    id: "reuters uk",
    name: "Reuters UK",
    category: "news",
  },
  {
    id: "the athletic",
    name: "The Athletic",
    category: "sports",
  },
]

export const NYT_CATEGORIES: CategoryOption[] = [
  { id: "arts", display: "Arts" },
  { id: "automobiles", display: "Automobiles" },
  { id: "autos", display: "Autos" },
  { id: "blogs", display: "Blogs" },
  { id: "books", display: "Books" },
  { id: "booming", display: "Booming" },
  { id: "business", display: "Business" },
  { id: "business day", display: "Business Day" },
  { id: "corrections", display: "Corrections" },
  { id: "crosswords & games", display: "Crosswords & Games" },
  { id: "crosswords/games", display: "Crosswords/Games" },
  { id: "dining & wine", display: "Dining & Wine" },
  { id: "dining and wine", display: "Dining and Wine" },
  { id: "editors' notes", display: "Editors' Notes" },
  { id: "education", display: "Education" },
  { id: "fashion & style", display: "Fashion & Style" },
  { id: "food", display: "Food" },
  { id: "front page", display: "Front Page" },
  { id: "giving", display: "Giving" },
  { id: "global home", display: "Global Home" },
  { id: "great homes & destinations", display: "Great Homes & Destinations" },
  {
    id: "great homes and destinations",
    display: "Great Homes and Destinations",
  },
  { id: "health", display: "Health" },
  { id: "home & garden", display: "Home & Garden" },
  { id: "home and garden", display: "Home and Garden" },
  { id: "international home", display: "International Home" },
  { id: "job market", display: "Job Market" },
  { id: "learning", display: "Learning" },
  { id: "magazine", display: "Magazine" },
  { id: "movies", display: "Movies" },
  { id: "multimedia", display: "Multimedia" },
  { id: "multimedia/photos", display: "Multimedia/Photos" },
  { id: "n.y./region", display: "N.Y./Region" },
  { id: "nyregion", display: "NYRegion" },
  { id: "nyt now", display: "NYT Now" },
  { id: "national", display: "National" },
  { id: "new york", display: "New York" },
  { id: "new york and region", display: "New York and Region" },
  { id: "obituaries", display: "Obituaries" },
  { id: "olympics", display: "Olympics" },
  { id: "open", display: "Open" },
  { id: "opinion", display: "Opinion" },
  { id: "paid death notices", display: "Paid Death Notices" },
  { id: "public editor", display: "Public Editor" },
  { id: "real estate", display: "Real Estate" },
  { id: "science", display: "Science" },
  { id: "sports", display: "Sports" },
  { id: "style", display: "Style" },
  { id: "sunday magazine", display: "Sunday Magazine" },
  { id: "sunday review", display: "Sunday Review" },
  { id: "t magazine", display: "T Magazine" },
  { id: "t:style", display: "T:Style" },
  { id: "technology", display: "Technology" },
  { id: "the public editor", display: "The Public Editor" },
  { id: "the upshot", display: "The Upshot" },
  { id: "theater", display: "Theater" },
  { id: "times topics", display: "Times Topics" },
  { id: "timesmachine", display: "TimesMachine" },
  { id: "today's headlines", display: "Today's Headlines" },
  { id: "topics", display: "Topics" },
  { id: "travel", display: "Travel" },
  { id: "u.s.", display: "U.S." },
  { id: "universal", display: "Universal" },
  { id: "urbaneye", display: "UrbanEye" },
  { id: "washington", display: "Washington" },
  { id: "week in review", display: "Week in Review" },
  { id: "world", display: "World" },
  { id: "your money", display: "Your Money" },
]
